init
GregorJosh/goit-project-02 pull request #28
Opened 2023-07-26 20:43 UTC by Weronika2003

2023-07-26 21:04 UTC, GregorJosh commented on package-lock.json
ten plik nie powinien być zmieniany, pracujemy tylko na plikach w folderze "src"

2023-07-26 21:05 UTC, GregorJosh commented on src/js/library.js
> +const localStorageData = {
Ta symulacja nie jest potrzebna

2023-07-26 21:06 UTC, GregorJosh commented on src/js/library.js
> +function getFromStorage(key) {
Ta funkcja nie jest potrzebna

2023-07-26 21:17 UTC, GregorJosh commented on src/js/library.js
> +const LOCAL_STORAGE_WATCH_KEY = 'watched';
Nie potrzebne jest tworzenie tych stałych bo te stałe są już utworzone w pliku app.js.

Czyli wystarczy tylko w miejscu gdzie są potrzebne odwołać się do nich, np:
  `localStorage.setItem(app.LOCAL_STORAGE_WATCH_KEY, movieObject);`

2023-07-26 21:18 UTC, GregorJosh commented on src/js/library.js
> +function getWatchedMovies() {
ta funkcja nie jest potrzebna

2023-07-26 21:25 UTC, GregorJosh commented on src/js/library.js
> +function getQueuedMovies() {
tak samo jak wyżej wyjaśniłem

2023-07-26 21:26 UTC, GregorJosh commented on src/js/library.js
> +function setWatchedMovies(array) {
ta funkcja jest niepotrzebna

2023-07-26 21:26 UTC, GregorJosh commented on src/js/library.js
> +  localStorageData[LOCAL_STORAGE_QUEUE_KEY] = array;
ta funkcja też nie jest potrzebna

2023-07-26 21:29 UTC, GregorJosh commented on src/js/library.js
> +const watchedData = getWatchedMovies();
cały kod od tego miejsca do końca jest nie potrzebny

2023-07-26 21:37 UTC, GregorJosh commented on src/js/library.js
> +const watchedData = getWatchedMovies();
wywołać funkcje trzeba będzie z obiektu app, gdyż w nim mają znajdować się funkcje globalne używane w wielu zadaniach przez kod różnych autorów.

Na przykład tak:
`const watchedData = app.getWatchedMovies();`

2023-07-26 21:50 UTC, GregorJosh commented on src/sass/index.css
nie powinny być wysyłane pliki css na github.
Style piszemy w plikach scss w folderze src/sass/components/[plik twojego zadania]. 
Jeśli pisałaś w plikach scss a i tak pojawiły się pliki css to może być dlatego że masz włączoną wtyczkę Live SASS Compiler w Visual Studio Code.

2023-07-26 21:52 UTC, GregorJosh requested changes
Napisałem w Pull Request szczegółowe komentarze co jest do zmiany

2023-07-27 14:34 UTC, Weronika2003 commented on package-lock.json
#Nie wiem czemu, ale bez zrobienia npm install nie działał mi npm start, wyłapywało błąd tam gdzie go nie było. Co w takim wypadku powinnam zrobić?

2023-07-27 15:10 UTC, GregorJosh commented on package-lock.json
Możesz dodać do pliku .gitignore nazwę tego pliku żeby nie był wysyłany

2023-07-27 17:56 UTC, GregorJosh approved these changes
jest ok, teraz poczekasz na funkcje wyświetlania, i potem ją wstawisz do swojego kodu

2023-07-27 17:59 UTC, merged